title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://thokall.github.io/test1
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter:
   facebook:
   email: thokall@me.com
